package:
  name: "py12box"
  version: 0.2.2

source:
  git_url: https://github.com/mrghg/py12box
  git_rev: v0.2.2
  git_depth: 1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy=1.21
    - numba=0.55
    - scipy
    - pandas

test:
  imports:
    - py12box

about:
  home: https://github.com/mrghg/py12box
  license: MIT
  license_family: MIT
  summary: AGAGE 12-box model
  doc_url: https://py12box.readthedocs.io
