package:
  name: "py12box"
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/mrghg/py12box
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_depth: 1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - numba
    - scipy

test:
  imports:
    - py12box

about:
  home: https://github.com/mrghg/py12box
  license: MIT
  license_family: MIT
  summary: AGAGE 12-box model
